sudo: false
language: node_js
node_js:
  - "6"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run cover
  - npm run check-coverage
  - npm run report-coverage

after_success:
  - npm run codecov